
# グラム : センサ値
weights :
    '0' : 756.5 # 初期値
    '10' : 751.1 # 分銅
    '20' : 745.8 # 分銅
    '30' : 749.45 # 分銅
    # '136.5' : 521.65 # HTC Desire
    # '101.5' : 540 # iPod touch 4G

# 音声ファイル : 重さ
# wavsディレクトリ下のファイルがアップロードされる
objects :
    'beer.wav' : 50
    'cup.wav' : 300

api : 'http://masui.sfc.keio.ac.jp/gyaco'
