
# グラム : センサ値
weights :
    '0' : 746.5 # 初期値
    '10' : 740.15 # 分銅
    '20' : 734.9 # 分銅
    '30' : 729.355 # 分銅
    # '136.5' : 521.65 # HTC Desire
    # '101.5' : 540 # iPod touch 4G

# 音声ファイル : 重さ
# wavsディレクトリ下のファイルがアップロードされる
objects :
    'beer.mp3' : 526
    'egg.mp3' : 300

api : 'http://example.com/gyaco'
